---
title: "Reanalysis of Yanagihara et al 2024"
date: '`r format(Sys.time(), "%Y-%m-%d", tz = "UTC")`'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reanalysis of Yanagihara et al 2024}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>"
)
```

```{r setup}
library(envirotox)
library(ssdtools)
```

```{r acute}
dists <- c("lnorm", "llogis", "burrIII3", "weibull")

data <- envirotox::yanagihara_24_acute |>
  dplyr::filter(BC <= 0.555) |>
  dplyr::nest_by(Chemical) |>
  dplyr::mutate(n = nrow(data), 
                ssd_fit = list(ssd_fit_dists(data, dists = dists, at_boundary_ok = FALSE, computable = TRUE, silent = TRUE))) |>
 # dplyr::filter(hasName(ssd_fit, "burrIII")) |>
  dplyr::mutate(ssd_hc = list(ssd_hc(ssd_fit, average = FALSE))) |>
  tidyr::unnest(ssd_hc)

data |>
  dplyr::group_by(Chemical) |>
  dplyr::arrange(desc(wt)) |>
  dplyr::slice(1) |>
  dplyr::ungroup() |>
  dplyr::count(dist) |>
  dplyr::arrange(desc(n)) |>
  print()

data |>
  dplyr::group_by(dist) |>
  dplyr::summarise(wt = mean(wt), .groups = "drop") |>
  dplyr::arrange(desc(wt)) |>
  print()
```

```{r acute default}

data <- envirotox::yanagihara_24_acute |>
  dplyr::filter(BC <= 0.555) |>
  dplyr::nest_by(Chemical) |>
  dplyr::mutate(n = nrow(data), 
                ssd_fit = list(ssd_fit_dists(data, silent = TRUE))) |>
 # dplyr::filter(hasName(ssd_fit, "burrIII")) |>
  dplyr::mutate(ssd_hc = list(ssd_hc(ssd_fit, average = FALSE))) |>
  tidyr::unnest(ssd_hc)

data |>
  dplyr::group_by(Chemical) |>
  dplyr::arrange(desc(wt)) |>
  dplyr::slice(1) |>
  dplyr::ungroup() |>
  dplyr::count(dist) |>
  dplyr::arrange(desc(n)) |>
  print()

data |>
  dplyr::group_by(dist) |>
  dplyr::summarise(wt = mean(wt), .groups = "drop") |>
  dplyr::arrange(desc(wt)) |>
  print()
```

```{r acute default no filter}

data <- envirotox::yanagihara_24_acute |>
  dplyr::nest_by(Chemical) |>
  dplyr::mutate(n = nrow(data), 
                ssd_fit = list(ssd_fit_dists(data, silent = TRUE))) |>
 # dplyr::filter(hasName(ssd_fit, "burrIII")) |>
  dplyr::mutate(ssd_hc = list(ssd_hc(ssd_fit, average = FALSE))) |>
  tidyr::unnest(ssd_hc)

data |>
  dplyr::group_by(Chemical) |>
  dplyr::arrange(desc(wt)) |>
  dplyr::slice(1) |>
  dplyr::ungroup() |>
  dplyr::count(dist) |>
  dplyr::arrange(desc(n)) |>
  print()

data |>
  dplyr::group_by(dist) |>
  dplyr::summarise(wt = mean(wt), .groups = "drop") |>
  dplyr::arrange(desc(wt)) |>
  print()
```
